import Foundation
import dBriefWire

/// AI analysis output persisted alongside a recording as `<base>.insights.json`.
/// Written during processing and rewritten when the user edits the analysis in
/// the transcript window. Sentiment is display-only (never edited by the user).
struct RecordingInsights: Codable, Sendable, Equatable {
    static let currentVersion = 1

    var version: Int
    var summary: String
    var actionItems: [String]
    /// Optional for backward compatibility. Exact raw-text keys retain an
    /// unchanged action's state; rewritten actions start unfinished.
    var completedActionItems: [String]? = nil
    var tags: [String]
    var sentiment: String
    /// Title generated by unified analysis engines before Markdown is written.
    /// Persisting it here avoids rerunning analysis after a restart.
    var generatedTitle: String?
    /// Absolute path of the markdown file generated for this recording, so an
    /// edit knows which `.md` to update. Nil/missing → markdown update skipped.
    var markdownPath: String?
    var basedOnPreviousTranscript: Bool? = nil
    var modelProvenance: AnalysisModelProvenance? = nil
    /// Raw per-part notes from map-reduce analysis of a long recording; nil for single-pass
    /// analyses and older sidecars. Gives Transcript Chat a whole-meeting overview.
    var partNotes: [ChunkNotes]? = nil

    var completedActions: Set<String> {
        Set(completedActionItems ?? []).intersection(actionItems)
    }

    var unfinishedActionItems: [String] {
        let completed = completedActions
        return actionItems.filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && !completed.contains($0) }
    }

    init(
        version: Int = currentVersion,
        summary: String,
        actionItems: [String],
        tags: [String],
        sentiment: String,
        generatedTitle: String? = nil,
        markdownPath: String?,
        modelProvenance: AnalysisModelProvenance? = nil,
        partNotes: [ChunkNotes]? = nil
    ) {
        self.version = version
        self.summary = summary
        self.actionItems = actionItems
        self.tags = tags
        self.sentiment = sentiment
        self.generatedTitle = generatedTitle
        self.markdownPath = markdownPath
        self.modelProvenance = modelProvenance
        self.partNotes = partNotes
    }

    enum CodingKeys: String, CodingKey {
        case version, summary, actionItems, completedActionItems, tags, sentiment, generatedTitle
        case markdownPath, basedOnPreviousTranscript, modelProvenance, partNotes
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        version = try c.decode(Int.self, forKey: .version)
        summary = try c.decode(String.self, forKey: .summary)
        actionItems = try c.decode([String].self, forKey: .actionItems)
        completedActionItems = try c.decodeIfPresent([String].self, forKey: .completedActionItems)
        tags = try c.decode([String].self, forKey: .tags)
        sentiment = try c.decode(String.self, forKey: .sentiment)
        generatedTitle = try c.decodeIfPresent(String.self, forKey: .generatedTitle)
        markdownPath = try c.decodeIfPresent(String.self, forKey: .markdownPath)
        basedOnPreviousTranscript = try c.decodeIfPresent(Bool.self, forKey: .basedOnPreviousTranscript)
        modelProvenance = try c.decodeIfPresent(AnalysisModelProvenance.self, forKey: .modelProvenance)
        // Lenient: a malformed or future-shaped notes payload must never make the sidecar unreadable.
        partNotes = try? c.decodeIfPresent([ChunkNotes].self, forKey: .partNotes)
    }

    /// User-friendly plain text for the Copy button. Omits empty sections.
    func plainTextForCopy() -> String {
        var parts: [String] = []
        let trimmedSummary = summary.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedSummary.isEmpty {
            parts.append("Summary\n\n\(trimmedSummary)")
        }
        if !actionItems.isEmpty {
            let body = actionItems.map { "- \($0)" }.joined(separator: "\n")
            parts.append("Action Items\n\n\(body)")
        }
        if !tags.isEmpty {
            let body = tags.map { "#\($0)" }.joined(separator: " ")
            parts.append("Tags\n\n\(body)")
        }
        let trimmedSentiment = sentiment.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedSentiment.isEmpty {
            parts.append("Sentiment: \(trimmedSentiment)")
        }
        return parts.joined(separator: "\n\n")
    }
}
